### ISSUE TITLE
Could you upload the plugin source code

### ISSUE THREAD

**Issue by Safraann** [gcWorld/IBISdroid#1]
Hello gcWorld, I try in despair for few days to run my OMSI plugin coded in Delphi, but pointlessly, nothing wants to work, logs tells me " LoadLibrary failed ", would it be possible to have your source code so that I can correct mine, or by uploading mine, can you correct it ? Thank you in advance ! =)

**Comment by gcWorld** [comment]
This is being discussed here: https://github.com/gcWorld/IBIScontrol-Bugs/issues/38
